AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot Demo API on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  DemoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: demo-api
      Handler: com.example.demo.StreamLambdaHandler
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt DemoApiFunction.Arn
